title: Brainsmith
description: Automated FPGA Dataflow Accelerator Generation

url: "https://kirthana1181.github.io"
baseurl: "/brainsmith.github.io"

theme: jekyll-theme-minimal

markdown: kramdown
highlighter: rouge

collections:
  docs:
    output: true
    permalink: /docs/:name/

defaults:
  - scope:
      path: ""
      type: docs
    values:
      layout: default
